# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4ec9b78758cb422393bc9556c80c13e5e834d291cca064d412d6d9cc0ea6bd34251353e41ddc33b49b6701ebd958f76bc4b48e8fd952894e39804aaa311bbaa

test:
  secret_key_base: 11d665f639d44b793d271d44184d455636dc1ae91638bce95220563a25d053290c9034ab622dc448c02d46e45cb41a2322425dfbeb3b81c8c993432d9ced37c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
